apiVersion: v1
kind: Pod
metadata:
  name: oom-target-pod
  namespace: default
spec:
  containers:
  - name: memory-hog
    image: alexeiled/stress-ng # Świetny obraz do testów obciążeniowych
    args: ["--vm", "1", "--vm-bytes", "10M", "--timeout", "60s"] # Prosi o 50MB RAMu
    resources:
      requests:
        memory: "20Mi"
        cpu: "100m"
      limits:
        memory: "20Mi" # Limit to tylko 20Mi! (QoS: Guaranteed)
        cpu: "200m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scalable-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scalable-app1
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # Chcemy skalować powyżej 50% z requests (czyli > 50m)