apiVersion: external-secrets.io/v1 # <- Zmiana tutaj
kind: SecretStore
metadata:
  name: fake-vault
  namespace: default
spec:
  provider:
    fake:
      data:
      - key: "cloud-database/credentials"
        value: '{"username": "admin_prod", "password": "SuperSecurePassword2026!"}'