apiVersion: external-secrets.io/v1 # <- Zmiana tutaj
kind: ExternalSecret
metadata:
  name: my-app-db-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: fake-vault
    kind: SecretStore
  target:
    name: local-k8s-secret
    creationPolicy: Owner
  data:
  - secretKey: DB_USER
    remoteRef:
      key: "cloud-database/credentials"
      property: username
  - secretKey: DB_PASSWORD
    remoteRef:
      key: "cloud-database/credentials"
      property: password