apiVersion: v1
kind: Pod
metadata:
  name: ml-pod
  namespace: default
spec:
  tolerations: # Tutaj dajemy podowi pozwolenie na wejście
  - key: "sku"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
  containers:
  - name: cuda-simulator
    image: nginx:alpine